### ISSUE TITLE
  Error Contents: No module named PIL.Image

### ISSUE THREAD

**Issue by achimfrase** [flathub/tv.kodi.Kodi#40]
The script.extendedinfo gives me an error when I try to view the actors info.
This happens if I press "up-key" on an Actor image.
I am using the default skin "Estuary".
![error](https://user-images.githubusercontent.com/45271246/52143511-fa9d4100-265b-11e9-89a9-842dc9b69aaf.jpg)
As it seems this problem is related to youtube.dl.
The error indicates that there is something missing from python (PIL.Image).

If you have any questions please let me know.

19:50:36.689 T:139900296881920  NOTICE: script.module.youtube.dl: youtube_dl core version: 2018.11.07
19:50:36.708 T:139900296881920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named PIL.Image
                                            Traceback (most recent call last):
                                              File "/home/afrase/.var/app/tv.kodi.Kodi/data/addons/script.extendedinfo/default.py", line 63, in <module>
                                                Main()
                                              File "/home/afrase/.var/app/tv.kodi.Kodi/data/addons/script.extendedinfo/default.py", line 37, in __init__
                                                listitems = process.start_info_actions(info, self.params)
                                              File "/home/afrase/.var/app/tv.kodi.Kodi/data/addons/script.extendedinfo/resources/lib/process.py", line 348, in start_info_actions
                                                name=params.get("name"))
                                              File "/home/afrase/.var/app/tv.kodi.Kodi/data/addons/script.extendedinfo/resources/lib/WindowManager.py", line 155, in open_actor_info
                                                from dialogs.DialogActorInfo import DialogActorInfo
                                              File "/home/afrase/.var/app/tv.kodi.Kodi/data/addons/script.extendedinfo/resources/lib/dialogs/DialogActorInfo.py", line 11, in <module>
                                                from kodi65 import imagetools
                                              File "/home/afrase/.var/app/tv.kodi.Kodi/data/addons/script.module.kodi65/lib/kodi65/imagetools.py", line 9, in <module>
                                                import PIL.Image
                                            ImportError: No module named PIL.Image
                                            -->End of Python script error report<--

**Comment by LiquidPrototype** [comment]
python3 -m pip install Pillow

**Comment by achimfrase** [comment]
I tested "Build 1825" from https://github.com/flathub/tv.kodi.Kodi/pull/39#issuecomment-460013511
and it works. Thanks a lot!

**Comment by Marko10-000** [comment]
@achimfrase is merged. In about an hour you can use the stable repository.

**Comment by achimfrase** [comment]
@Marko10-000 Thanks!
